// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_250_without_bonus = "CgkIp7jc_LgZEAIQCg"; // <GPGSID>
        public const string achievement_for_the_horde = "CgkIp7jc_LgZEAIQAg"; // <GPGSID>
        public const string achievement_for_the_gold = "CgkIp7jc_LgZEAIQBA"; // <GPGSID>
        public const string achievement_counter_the_devil = "CgkIp7jc_LgZEAIQDg"; // <GPGSID>
        public const string achievement_lucky_you = "CgkIp7jc_LgZEAIQAA"; // <GPGSID>
        public const string leaderboard_high_score = "CgkIp7jc_LgZEAIQAQ"; // <GPGSID>
        public const string achievement_wombo_combos = "CgkIp7jc_LgZEAIQDQ"; // <GPGSID>
        public const string achievement_for_the_forest = "CgkIp7jc_LgZEAIQAw"; // <GPGSID>
        public const string achievement_poor_you = "CgkIp7jc_LgZEAIQBQ"; // <GPGSID>
        public const string achievement_750 = "CgkIp7jc_LgZEAIQCA"; // <GPGSID>
        public const string achievement_750_without_bonus = "CgkIp7jc_LgZEAIQDA"; // <GPGSID>
        public const string achievement_500 = "CgkIp7jc_LgZEAIQBw"; // <GPGSID>
        public const string achievement_250 = "CgkIp7jc_LgZEAIQBg"; // <GPGSID>
        public const string achievement_catch_em_all = "CgkIp7jc_LgZEAIQCQ"; // <GPGSID>
        public const string achievement_500_without_bonus = "CgkIp7jc_LgZEAIQCw"; // <GPGSID>
        public const string achievement_200_volts = "CgkIp7jc_LgZEAIQDw"; // <GPGSID>

}

